@startuml "Master Class Diagram - DDD Architecture"

' Configuración visual global
skinparam packageStyle rectangle
skinparam shadowing false
skinparam handwritten false
skinparam classAttributeIconSize 0

' Dirección de renderizado
top to bottom direction

' Inclusión modular de Bounded Contexts
!include bc-01-user-registration.puml
!include bc-02-search.puml
!include bc-03-vocational-evaluation.puml
!include bc-04-career-exploration.puml
!include bc-05-student-monitoring.puml
!include bc-06-reports.puml
!include bc-07-payment-subscription.puml
!include bc-08-scheduling-session.puml
!include bc-09-community-chat.puml
!include bc-10-system-notifications.puml

@enduml